POST http://localhost:8000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjY2MTk4OTYsImlkIjoiY2U3YTc1ZDYtMGU0My00ZmY1LThkZjUtNjcwMjZiOWQwM2FhIn0.2TkyYDLidvCJH9qRuRxuTusAiUHrb_D9-2DNnxfoxik

{
  "name": "Product 235",
  "price": 4577
}

###

GET http://localhost:8000/product/bf1fde6e-722a-4eef-9cc8-fc03f823f15b

###

GET http://localhost:8000/product?page=1&limit=3&sort=desc

###

PUT http://localhost:8000/product/154e2f1c-160a-4146-88b1-3e01dd4730f4
Content-Type: application/json

{
  "name": "Product 1 Updated",
  "price": 200
}

###

DELETE http://localhost:8000/product/154e2f1c-160a-4146-88b1-3e01dd4730f4