POST http://localhost:8000/user
Content-Type: application/json

{
  "name": "John Dodo",
  "email": "jonhdodo@jojo.com",
  "password": "123456"
}

###

POST localhost:8000/user/getToken
Content-Type: application/json

{
  "email": "jonhdodo@jojo.com",
  "password": "123456"
}